## The following functions take an invertible matrix and create a version of that matrix
## stored as x that supports caching the inverse. The matrix is accessible by x$get().
## If the inverse has not been calculated, cacheSolve(x) will calculate the inverse and store it
## (accessible by x$getinv()). If the inverse has already been calculated, cacheSolve(x) will display
## "getting cached data" and then print the stored inverse.

## makeCacheMatrix receives a matrix x and creates a list usable by cacheSolve to calculate and store the
## inverse of x.

makeCacheMatrix <- function(x = matrix()) {
  s <- NULL
  set <- function(y) {
    x <<- y
    s <<- NULL
  }
  get <- function() x
  setinv <- function(solve) s <<- solve
  getinv <- function() s
  x <<- list(set = set, get = get,
       setinv = setinv,
       getinv = getinv)
}


## cacheSolve receives a list generated by makeCacheMatrix and returns the inverse of the matrix fed to
## makeCacheMatrix. If the inverse has already been calculated by cacheSolve, a message will be displayed
## saying "getting cached data" and then the inverse will be displayed. If the inverse has not been
## calculated by cacheSolve, cacheSolve will calculate and store the inverse, then display it.

cacheSolve <- function(x, ...) {
  ## Return a matrix that is the inverse of 'x'
  s <- x$getinv()
  if(!is.null(s)) {
    message("getting cached data")
    return(s)
  }
  data <- x$get()
  s <- solve(data, ...)
  x$setinv(s)
  s
}
